format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$character"""

right_format = """
$cmd_duration"""

[directory]
style = "cyan"
use_os_path_sep = false
fish_style_pwd_dir_length = 3
truncate_to_repo = false

[directory.substitutions]
"C:/msys64/home/akuna" = "~"

[character]
success_symbol = "[>](bright-green)"
error_symbol = "[>](bright-red)"

[git_branch]
format = "[$branch]($style)"
style = "bright-green"

[git_status]
format = '( $ahead_behind)( $conflicted)( $untracked)( $modified)( $staged)( $renamed)( $deleted) '
style = "green"
ahead = '[>${count}](green)'
behind = '[<${count}](green)'
up_to_date = ''
diverged = '[>${ahead_count} <${behind_count}](green)'
conflicted = '[~${count}](red)'
untracked = '[?${count}](cyan)'
modified = '[!${count}](yellow)'
staged = '[+${count}]($style)'
renamed = '[>>${count}]($style)'
deleted = '[x${count}](red)'
stashed = "≡[${count}]($style)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-green"

[cmd_duration]
format = "[$duration]($style) "
style = "bright-gray"
